### ISSUE TITLE
https://linux.pictures website is down

### ISSUE THREAD

**Issue by carlwgeorge** [LaniJW/linux-pictures#1]
The site referenced in the README, https://linux.pictures, doesn't appear to be working.  Did it move to a new domain?

**Comment by meredithheskethfortescue** [comment]
I want it back too! I especially admire the license...

**Comment by LaniJW** [comment]
This is just a clone of the old repo. I don't own the pictures. I just got the pictures because a reddit post suggested the repo will be deleted. There seems to be something on [linux.pictures](http://www.linux.pictures) now though.
